name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup runtime
        run: echo "Install dependencies"

      - name: Lint
        run: echo "Run lint"

      - name: Unit Tests
        run: echo "Run tests"

      - name: Build
        run: echo "Build application"
